require("susvim.options")
require("susvim.keymaps")
require("susvim.plugins")
require("susvim.cmp")
require("susvim.copilot")
require("susvim.lsp")
require("susvim.telescope")
require("susvim.treesitter")

vim.cmd("colorscheme catppuccin")
